# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.2/scratchmd_darwin_amd64.tar.gz"
      sha256 "326452bba7b273bf9336129090be2395a8d98a53f407672ffb5adb6105770c1d"

      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.2/scratchmd_darwin_arm64.tar.gz"
      sha256 "7346eca833d2f0ad31cfaa5d41b65e5352adbfb61e89fa2e59169d9ff403c7e3"

      def install
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.2/scratchmd_linux_amd64.tar.gz"
      sha256 "155027825074134881d8249bf792c33f645f4a16b5d1982ffb22ee6ceb427d28"
      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.2/scratchmd_linux_arm64.tar.gz"
      sha256 "3a4936da1904f653cf485f3fa35e4bad83ebc7dfe53f345ed0803d053801862b"
      def install
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
