# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.3/scratchmd_darwin_amd64.tar.gz"
      sha256 "b16cde256ef8299b3a6616da77f9de33db93a7101de3878334c7eee4259ab892"

      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.3/scratchmd_darwin_arm64.tar.gz"
      sha256 "9d9eba53f3868afab6d4bb7a4daadb275b92b4245ea430a5c43d587c864292f7"

      def install
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.3/scratchmd_linux_amd64.tar.gz"
      sha256 "0ab376bc1e494013f653dcc7760146c11949eedc23d47ca3e6cdff3fd3b4385d"
      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.1.3/scratchmd_linux_arm64.tar.gz"
      sha256 "0678768005b83c9772c1fa1e51bf02de0dac12fcd1c19976e964eb594cb8b5d4"
      def install
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
